name: RickMorty API tests on push

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '8.0.292+10'

    - name: Install dependencies
      run: mvn install -DskipTests
      working-directory: ./rickMortyAPITests

    - name: Build with Maven
      run: mvn clean install
      working-directory: ./rickMortyAPITests

    - name: Run tests
      run: mvn test
      working-directory: ./rickMortyAPITests

    - name: Generate cucumber report
      run: mvn verify
      working-directory: ./rickMortyAPITests

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports
        path: ./rickMortyAPITests/target/cucumber-html-reports

