name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '8.0.292+10'

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test

    - name: Generate cucumber report with debug info
      run: mvn verify -e -X

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: cucumber-reports
        path: target/cucumber-html-reports